### ISSUE TITLE
Error validation

### ISSUE THREAD

**Issue by Gustavinho** [yaronn/xml-crypto#81] opened 2015-11-25 23:40 UTC
Hi, I'm validating an XML signed by xml-crypto, but always returns me a invalid message, I've attached the signed xml, the public key, and my coffeescript code to sign and verify

could you help me whit that please?

to sign

    sign = new SignedXml()
    sign.addReference "//*[local-name(.)='ConsultaSectorPrimario']" , "" , "" , "" , "" , "" , true
    sign.keyInfoProvider = new MyKeyInfo( rfc )
    sign.signingKey = fs.readFileSync( "./certificados/" + rfc + ".key.pem" )
    sign.computeSignature xml
    xml = 
    [JAEP820923NM9_publicKey.key.pem.txt](https://github.com/yaronn/xml-    crypto/files/44482/JAEP820923NM9_publicKey.key.pem.txt)
    [JAEP820923NM9_publicKey.key.pem.txt](https://github.com/yaronn/xml-    crypto/files/44483/JAEP820923NM9_publicKey.key.pem.txt)

    [JAEP820923NM9-AOPF580423BIA.txt](https://github.com/yaronn/xml-crypto/files/44484/JAEP820923NM9-AOPF580423BIA.txt)

    sign.getSignedXml()

to verify

    select = require('xml-crypto').xpath
    dom = require('xmldom').DOMParser
    SignedXml = require('xml-crypto').SignedXml
    FileKeyInfo = require('xml-crypto').FileKeyInfo

    doc = new dom().parseFromString(xml)
    signature = select(doc, "/*/*[local-name(.)='Signature' and namespace-    uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0]
    sig = new SignedXml()
    sig.keyInfoProvider = new FileKeyInfo( "./certificados/" + receptor + "_publicKey.key.pem" )
    sig.loadSignature(signature.toString())
    res = sig.checkSignature(xml)    console.log(sig.validationErrors) if !res

**Comment by yaronn** [comment] 2015-11-25 23:43
where is the xml?

**Comment by Gustavinho** [comment] 2015-11-25 23:46
I attached you the xml and the public key
[JAEP820923NM9-AOPF580423BIA.txt](https://github.com/yaronn/xml-crypto/files/44486/JAEP820923NM9-AOPF580423BIA.txt)
[JAEP820923NM9_publicKey.key.pem.txt](https://github.com/yaronn/xml-crypto/files/44487/JAEP820923NM9_publicKey.key.pem.txt)

**Comment by yaronn** [comment] 2015-11-25 23:51
this xml already contains a signature, why do you sign it again? try all of this on a very simple xml (1-2 tags) to see if it works on that.

**Comment by Gustavinho** [comment] 2015-11-26 00:00
I'm trying with <node>hello</node> and 
sign = new SignedXml()
sign.addReference "//*[local-name(.)='node']" , "" , "" , "" , "" , "" , true 

but it doesn't work

**Comment by Gustavinho** [comment] 2015-11-26 00:01
sorry 
notSigned = '<node>hello</node>'

**Comment by Gustavinho** [comment] 2015-11-26 00:02
sorry , the xml I'm using now is from attached image
![captura de pantalla 2015-11-25 a las 6 02 11 p m](https://cloud.githubusercontent.com/assets/4228757/11412166/b12cabbc-939e-11e5-8143-1709833fa87f.png)

**Comment by yaronn** [comment] 2015-11-26 00:05
try this using null instead of empty strings in addReference.

**Comment by Gustavinho** [comment] 2015-11-26 00:10
I tried with null instead empty strings, but I had the same result
sign.addReference "//*[local-name(.)='node']" , null , null , null , null , null , true

**Comment by yaronn** [comment] 2015-11-26 00:12
does it work if you just give addReference the first parameter (I know it will create the wrong URI but lets see if at least it gets the signature correctly).

**Comment by yaronn** [comment] 2015-11-26 00:14
if it fails try the example file or readme sample of the project. if it works try to hard code here to use the empty uri value:

https://github.com/yaronn/xml-crypto/blob/master/lib/signed-xml.js#L560

**Comment by bjrmatos** [comment] 2015-11-26 00:35
the problem is that you must sign your xml with the enveloped signature transform (because the signature will live inside the node you are signing)

**Comment by bjrmatos** [comment] 2015-11-26 00:39
try using:

(example in js)

```js
signGenerator.addReference(
    "//*[local-name(.)='ConsultaSectorPrimario']",
    [
      'http://www.w3.org/2000/09/xmldsig#enveloped-signature',
      'http://www.w3.org/2001/10/xml-exc-c14n#'
    ],
    null,
    '',
    '',
    '',
    true
);

```

**Comment by bjrmatos** [comment] 2015-11-26 00:41
that should work.. if it doesn't work please create a repository with your original xml, a dumb private/public key and the code you are using.

**Comment by yaronn** [comment] 2015-11-26 00:43
good call @bjrmatos!

**Comment by Gustavinho** [comment] 2015-11-26 00:54
woooooow, that it works, good one @bjrmatos, thanks, now I'm getting a successful validate, the web validator https://www.aleksey.com/xmlsec/xmldsig-verifier.html still says "invalid signature" but it doesn't care, thaks so much

**Comment by Gustavinho** [comment] 2015-11-26 01:38
I have a question, can I sign a xml twice? I mean a second sign of an xml with a first sign

first xml to sign
<ConsultaSectorPrimario rfcEmisor="AOPF580423BIA" rfcReceptor="JAEP820923NM9" rfcPrestadorAutorizado="AHO0505163C7" tsSolicitud="2015-11-25T19:36:37">

second xml to sign
<ConsultaSectorPrimario rfcEmisor="AOPF580423BIA" rfcReceptor="JAEP820923NM9" rfcPrestadorAutorizado="AHO0505163C7" tsSolicitud="2015-11-25T19:36:37"><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>luKNpO3MUBqHNkli3laDMEmAqq8=</DigestValue></Reference></SignedInfo><SignatureValue>QhqzxLh2HqUsXPsnUua9H+oNUthnB8G30CnUQs9kWAzZddTR0Eew4zaevtHtiJkY9Fc/hehDK/7Bgipo4nskVhCu7pC/EOSNKKeFJmyFRH1cOY7lvPXZ+ROuGWZ5anCd7U0fX/S50QTGzN4uaHzn2oPuZv3t6L3tSF20HBRTgoM=</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIFgzCCA2ugAwIBAgIUMjAwMDEwMDAwMDAzMDAwMDM1OTEwDQYJKoZIhvcNAQEFBQAwggFmMSAwHgYDVQQDDBdBLkMuIDIgZGUgcHJ1ZWJhcyg0MDk2KTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMSkwJwYJKoZIhvcNAQkBFhphc2lzbmV0QHBydWViYXMuc2F0LmdvYi5teDEmMCQGA1UECQwdQXYuIEhpZGFsZ28gNzcsIENvbC4gR3VlcnJlcm8xDjAMBgNVBBEMBTA2MzAwMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQRGlzdHJpdG8gRmVkZXJhbDESMBAGA1UEBwwJQ295b2Fjw6FuMRUwEwYDVQQtEwxTQVQ5NzA3MDFOTjMxITAfBgkqhkiG9w0BCQIMElJlc3BvbnNhYmxlOiBBQ0RNQTAeFw0xNDA2MDQyMTU3MjFaFw0xODA2MDMyMTU3MjFaMIHBMRwwGgYDVQQDExNQRURSTyBKQUlNRSBFU1RSQURBMRwwGgYDVQQpExNQRURSTyBKQUlNRSBFU1RSQURBMRwwGgYDVQQKExNQRURSTyBKQUlNRSBFU1RSQURBMQswCQYDVQQGEwJNWDEjMCEGCSqGSIb3DQEJARYUY29ycmVvMTIzQHBydWViYS5jb20xFjAUBgNVBC0TDUpBRVA4MjA5MjNOTTkxGzAZBgNVBAUTEkpBRVA4MjA5MjNNREZSTk4wOTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAxITUZwYJkqZTeI9tv6QSNzBm7mPrP3fEGKJbKo1wLJm5qyJ+ufkQw+UJRJetePn/hL47JdSFie0TOWDExheMF6Gnggjz5e/U96vl941NZPZJdLNnctXKJS8OFsmsXUFw8UHYtORBZYbtG9sclRv95NjNfAktVTfeIu7fhkojV3ECAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQUFAAOCAgEAbBzUG8JPtlQYGBEa3r8mwQLJwZEuPYJsVmYsrIdZYcEXHHwrqHNyEetgua4ZtMloxnPc+gNMK6LO0Mvqm8mMtEmOhmKZNky+7uhlrbA8ZOIzsbCCvjGCx+J+Pa5kO9A/htPLWvj1XBjwV6xkGo8DRWWAvu7GG6Ep/aojTMkQraLdHHkSyzCDrZPsmLktjT+fZNQ8XM8qINAMyke9vjl431ng/RWdDIVXvPrtsKizTFCY5a/YyoYor+qlNO8Bzp6cIFRwhIyCMH/apQ7TuqTKN79TzroY0iU/8kljfU40ftRtWJ1vhDSVSc16b7euGktx5XZ4EUrEiFgs+e/1FbVBquhrGm8FkpsQfX79IMhsbkem7CgFFC89HGDDKyaQkd+unpws+txsyvL5YpZozbf/B0geLFuFN8xtr7X9F0lhYcYQLX9f+o1r9usGxmysVt3aded8Fy8oUfFfrjhJcoGIj3bHToRPAmdQ0mgEXvhhO5vTNo2uT9MwWxL2f/W1awUYTAYcj+B+q5IC7XvCVfIlcd17LA+BK7hM+5TUmccYdC7oRBP/Hq+/OpHYz0fRfkzBoL46S520OH4x7Hx3jHfxLBkNsgnCLRTRqvU//uKkQgxwG4NPOmZeOoQCNQSjagl/DpYEGM78FJ9nBATcy/WuHlA9qSMbEXvFxgdM1k6cQzw=</X509Certificate></X509Data></KeyInfo></Signature></ConsultaSectorPrimario>

**Comment by Gustavinho** [comment] 2015-11-26 01:40
I have a question, can I sign a xml twice? I mean a second sign to a xml previously signed

first xml
![primerxml](https://cloud.githubusercontent.com/assets/4228757/11413234/60993554-93ac-11e5-858a-2d47bd9d80d8.png)
segundo xml
![segundoxml](https://cloud.githubusercontent.com/assets/4228757/11413236/665d47c8-93ac-11e5-9713-dda4e65df243.png)

**Comment by Gustavinho** [comment] 2015-11-26 01:41
I have a question, can I sign a xml twice? I mean a second sign to a xml previously signed and includes both signs

first xml
![primerxml](https://cloud.githubusercontent.com/assets/4228757/11413250/80edf06a-93ac-11e5-8625-b3f4f454be84.png)
second xml
![segundoxml](https://cloud.githubusercontent.com/assets/4228757/11413252/85ae181e-93ac-11e5-802b-375a0658d108.png)

**Comment by Gustavinho** [comment] 2015-11-26 01:42
I have a question, can I sign a xml twice? I mean a second sign to a xml previously signed and includes both signs

first xml to sign
![primerxml](https://cloud.githubusercontent.com/assets/4228757/11413254/99c8ca24-93ac-11e5-839c-fc8edaac48aa.png)
second xml to sign
![segundoxml](https://cloud.githubusercontent.com/assets/4228757/11413256/9efe5874-93ac-11e5-84f8-f16eb4faf290.png)

**Comment by bjrmatos** [comment] 2015-11-26 06:08
mmm technically, you can (i'm sure xml-crypto let you do that) but i don't know if it is valid according the XML Digital Signature Spec, i haven't seen a xml with a re-signature but maybe @yaronn know more about this

**Comment by Gustavinho** [comment] 2015-11-26 15:02
I don't think it'll be valid to the standard, but is a requirement of electronical invoice in México,  I tried to do it but the first and the second sign has the same digestvalue always, I don't know if it'll be ok

**Comment by bjrmatos** [comment] 2015-11-26 16:01
i'm closing this because is not an issue, feel free to keep comment.

mmm interesting, i have implemented electronical invoice in Perú.. in that case there is no need for re-sign the document. if i understand correctly mexico (and other countries in south america) use the UBL standard for electronical invoices, is that correct?

**Closed** 2015-11-26 16:01 UTC

**Comment by Gustavinho** [comment] 2015-11-26 16:17
Peru uses the UBL standard, but Mexico don't, Mexico has own standard, and it has many different process, one of them requires a resigned xml, and I just read that also requires a canonicalization method 1.1, I don't know if xml-crypto supports this method

**Comment by bjrmatos** [comment] 2015-11-26 16:33
xml-crypto support canonicalization methods and extending with custom canonicalization methods, but i don't know how the canonicalization 1.1 works (maybe is just one of the supported canonicalization methods that xml-crypto have but with other name).



> I don't think it'll be valid to the standard, but is a requirement of electronical invoice in México, I tried to do it but the first and the second sign has the same digestvalue always, I don't know if it'll be ok

if you create a repository, i can help you to test the re-sign to a document. unfortunately i don't know coffeescript so you should create the repository in JavaScript (it is short code anyway)

**Comment by Gustavinho** [comment] 2015-11-26 16:38
Thanks so much, I'll create a repository in javascript, and now I have an exact example with the xml signes an resigned, I'll also add it to repository
