### ISSUE TITLE
How to add <SignatureProperties> into signature?

### ISSUE THREAD

**Issue by stefnnn** [yaronn/xml-crypto#63] opened 2015-08-05 19:44 UTC
My use case requires me to add a timestamp to the signature within the <Signature> element. See below for an XML example. Adding additional objects to the signature is foreseen by the standard. But where would be a good place to insert such additional XML-Nodes into the code? This additional node should of course be signed as well, to prove that indeed the signature is from a certain time & date.

Any help appreciated... struggling with this xml mess :-(

    Signature
    ...
        Object Id="SignatureProperties"> <SignatureProperties xmlns="">
            SignatureProperty Target="#PaymentSignature" Id="TimeStamp"> 
                TimeStamp>
                    Date>2009-01-22 /Date
                    Time>14:59:33.3823239+01:00 /Time
                /TimeStamp>
            /SignatureProperty>
          /SignatureProperties>/Object
    /Signature

**Comment by yaronn** [comment] 2015-08-06 04:21
I've never seen custom nodes before inside the signature. since you need those nodes to be signed this would require custom development in signed-xml.js. a hack might be to add the new node outside the signature and sign it like a regular reference, then after the signature is generated move it to inside the signature (will work depending on the algorithm used and if you need it inside SignedInfo or just signature).

**Comment by stefnnn** [comment] 2015-08-07 11:11
Hi Yaron, 
thanks for your suggestions. I further checked the docs. Indeed the [Object] node wrapping the [SignatureProperties] should be signed with a reference and then added to the Signature-node (not inside SignedInfo). It's quite a challenge with the existing flow in the library. I'll give it a shot, but I fear that it won't be pretty to contribute back to the library...

**Comment by yaronn** [comment] 2015-08-08 04:34
don't worry about contributing to the lib. just complete your use case the best way you can. if after that you will have some tips for anyone implementing something similar in the future would be great if you can share them here.

**Comment by bjrmatos** [comment] 2015-09-05 05:13
since this is not a bug with xml-crypto i'm closing the issue.. feel free to keep comment :)

**Closed by bjrmatos** 2015-09-05 05:13 UTC
